### ISSUE TITLE
Cannot sign into to YT Music through any method

### ISSUE THREAD

**Issue by mattjescobar** [linsomniac/spotify_to_ytmusic#83]
Whenever I try to sign in either through the gui or ytmusicapi oauth or s2yt_ytoauth, google returns "something went wrong" and then kicks me to myaccount.google.com
![image](https://github.com/linsomniac/spotify_to_ytmusic/assets/43800608/cd5c5b77-c2b8-406d-af52-375fdf7220d9)

**Comment by CY83R-3X71NC710N** [comment]
This should be fixed in recent versions of the program.

**Comment by Speedy2662** [comment]
> This should be fixed in recent versions of the program.

That's not very helpful. I'm on the last version and still experiencing this problem.
